container:
  image:
    tag: 2.9.22-alpine

service:
  merge:
    spec:
      type: LoadBalancer

config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 1Gi
  merge:
    00$include: auth.conf

configMap:
  merge:
    data:
      auth.conf: |
        accounts {
            $SYS: {
                users: [{user: admin, password: admin}]
            },
        }


podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

extraResources:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    namespace:
      $tplYamlSpread: >
        {{ include "nats.metadataNamespace" $ }}
    name:
      $tplYaml: >
        {{ include "nats.fullname" $ | quote }}
    labels:
      $tplYaml: |
        {{ include "nats.labels" $ }}
  spec:
    rules:
    - http:
        paths:
        - backend:
            service:
              name:
                $tplYaml: >
                  {{ .Values.headlessService.name | quote }}
              port:
                number: 8222
          path: /
          pathType: Prefix
